/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "code-platform"
include("websites")
include("core")
include("platform-api")
include("platform-api:platform-application")
include("platform-api:adapter")
include("platform-api:adapter:platform-persistence-postgres")
include("platform-api:adapter:platform-entrypoint-rest")
